### ISSUE TITLE
1º Banana hangout

### ISSUE THREAD

**Issue by afonsopacifer** [bananacss/bananacss#21]
# 1º Banana hangout
![minions-funny-gif-GiNyo8KD5j9mM](https://camo.githubusercontent.com/bffbea2f69c0133821432f107ecbea81399e8131/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f47694e796f384b44356a396d4d2f67697068792e676966>)

## Participantes:
- @afonsopacifer
- @nathpaiva
- @danilovaz
- @jjaderg (stealth mode)

## O que rolou:
Apresentação dos objetivos do projeto e primeiras features.

## Objetivo:
 Colher feedbacks e gerar ideias.

### Grid:

*Banana code:*

```css
.row {
    bnn-width: 900px;
    bnn-position: center;
    bnn-align: left top;
}

.column {
    bnn-col: 4 12 2px; /* cols | total of cols | margins */
}
```

*CSS result*

```css
.row {
    width: 100%;
    max-width: 900px;
    display: block;
    margin-left: auto;
    margin-right: auto;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
    align-items: flex-start;
}

.column {
    margin-right: 2px;
    margin-left: 2px;
    width: x%; /*  x = ((100% * 4) / 12) - (2px * 2) */
}
```

### Box model:

*Banana code:*
```css
* {
    bnn-box: default;
    bnn-box: content;
}
```

*CSS result*
```css
* {
    box-sizing: border-box;
    box-sizing: content-box;
}
```
